enum class Instruction {
    VAL, VAR, IF, WHILE, PRINT, INPUT,
    CONTINUE, FUNC, FUNC_CALL, RETURN, FOR,
    START_POINT, END_POINT, OPERATOR_BLOCK, BREAK,
    GET_VALUABLE, END_IF, INITIALIZATION, SET
}